### ISSUE TITLE
Globe picture on homepage

### ISSUE THREAD

**Issue by akrych** [ipfs-shipyard/peer-pad#108]
Just design thing ;) we need add the globe illustration on homepage. 
Without it the page looks unfinished ;) (image is on drive)

![image](https://user-images.githubusercontent.com/22168118/32407900-dc59f65c-c18f-11e7-9af4-944b6f4547a8.png)

**Comment by jacobheun** [comment]
Resolved by https://github.com/ipfs-shipyard/peer-pad/pull/148
