### ISSUE TITLE
Stars on the top banner - homepage

### ISSUE THREAD

**Issue by akrych** [ipfs-shipyard/peer-pad#109]
We need add stars to the top banner background at home page, like on project: 
(picture is on drive)

![image](https://user-images.githubusercontent.com/22168118/32408018-997ea254-c191-11e7-9a85-185d80673456.png)

**Comment by pgte** [comment]
@akrych can't seam to find individual image, and I don't have the capability to parse the .psd. Could you please produce this image and put it on the drive? Thanks!

**Comment by akrych** [comment]
Sure, I add it on drive :) 👍

**Comment by jimpick** [comment]
We've removed the landing page (for now), so I'm going to close this.
