### ISSUE TITLE
Pad type dropdown not obvious it's a dropdown

### ISSUE THREAD

**Issue by victorb** [ipfs-shipyard/peer-pad#111]
![image](https://user-images.githubusercontent.com/459764/32408186-d347f790-c161-11e7-9cd7-ae5706c92f0c.png)

Had some people trying out PeerPad but not realizing there is a code pad. My guess is because it's not obvious that the dropdown is actually a dropdown. Maybe a caret would help?

**Comment by jimpick** [comment]
We've removed that landing page for now, so I'm closing this.
