### ISSUE TITLE
Does not work on Safari 11

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peer-pad#115]
Fails silently, it's unable to find and connect to other nodes. No console log.
IPFS: 0.26.0
Safari: 11.0.1

**Comment by dignifiedquire** [comment]
Probably same issue, doesn’t work on latest iOS Safari for me v11.0.3

**Comment by gedw99** [comment]
What's the failure ?
Is it the crappy indexdb support in safari.
What versions are you on 
What about iOS ?

**Comment by diasdavid** [comment]
It has worked for me multiple times in Safari, I've done demos with it. What is the problem still?
