### ISSUE TITLE
Create a staging environment

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/peer-pad#152]
It'd be great to be able to deploy master to dev.peerpad.net automagically from Jenkins, and explicitly pick a version to publish to peerpad.net once we're happy that a given version is sound.

This isn't a replacement for more automated testing. Peerpad is relied on as a public demonstration of ipfs capabilities, so we need both.

cc @VictorBjelkholm @diasdavid

**Comment by jacobheun** [comment]
@VictorBjelkholm with #182 merged, we should now have access to dev.peerpad.net. It looks like there is no DNS setup for that though. How can we go about getting that added/configured?

**Comment by pgte** [comment]
@jimpick It looks like we should start doing this without using your own PC :)
Would you take this one on?

**Comment by jacobheun** [comment]
This should be done (aside from updating docs), the caveat is that dev.peerpad.net uses the ipfs.io certificate. So to avoid ssl it needs to be loaded over ipfs.io: https://ipfs.io/ipns/dev.peerpad.net.  I verified this has the most recent change from master.

**Comment by victorb** [comment]
This is working [since wildcard certs](https://github.com/protocol/infra/commit/a63943231de417a05db3baa0254479663aff123f) were added to *.peerpad.net. So https://dev.peerpad.net will now show the latest commit from master
