### ISSUE TITLE
Was this repo renamed from "peerpad"?

### ISSUE THREAD

**Issue by lgierth** [ipfs-shipyard/peer-pad#161]
I'm pretty sure it was named peerpad - it's named peerpad everywhere else. Is it about the peer star work?

**Comment by VictorBjelkholm** [comment]
Yes, it was. https://github.com/ipfs-shipyard/peerpad redirects to here, so evidence of a rename.

**Comment by olizilla** [comment]
Yes, i think they all were, https://github.com/ipfs-shipyard/peer-pad-core used to be peerpad-core
