### ISSUE TITLE
Jenkins intermittently fails with permission denied

### ISSUE THREAD

**Issue by jacobheun** [ipfs-shipyard/peer-pad#167]
Jenkins will occasionally fail attempting to open the ipfs repo lock. Re-running the build again will eventually succeed.

Here is a link to an example failure: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%20Shipyard%2Fpeer-pad/detail/PR-160/3/pipeline/

The builds stack trace:
```
Error: cannot acquire lock: Lock Create of /home/ubuntu/.ipfs/repo.lock failed: open /home/ubuntu/.ipfs/repo.lock: permission denied

script returned exit code 1
```

**Comment by jacobheun** [comment]
@VictorBjelkholm do you have an idea of why this would be happening?

**Comment by miguelmota** [comment]
@jacobheun getting this same issue on circleci, did you find a resolution?

**Comment by jacobheun** [comment]
@miguelmota we haven't looked into this too much, but there is likely an order of operations issue going on here.

Are you running peer-pad in circleci or a different app that uses ipfs?

**Comment by miguelmota** [comment]
@jacobheun a different app that uses IPFS. It was fixed it though by not running IPFS as root

**Comment by jimpick** [comment]
PR #294 moved the deploy to CircleCI.
