### ISSUE TITLE
What is a math pad?

### ISSUE THREAD

**Issue by one000mph** [ipfs-shipyard/peer-pad#174]
@designsaves has been auditing the current interface and preparing for upcoming front-end work. We couldn't access the math pad feature that is described in this PR https://github.com/ipfs-shipyard/peer-pad-core/pull/2. It looks like the work has already been done in the code though. Is this a feature that you'd like to keep? cc @pgte

**Comment by pgte** [comment]
A math pad is a markdown pad that accept the markdown math extensions.
It's currently available in production by choosing "Math pad" in the pad type dropdown:
<img width="477" alt="peerpad" src="https://user-images.githubusercontent.com/47910/40621333-47dfea62-6294-11e8-9531-0b57cad655b4.png">

Yes, I would like to keep this feature.
