### ISSUE TITLE
Afdter running for a while - Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/peer-pad#198]
<img width="943" alt="image" src="https://user-images.githubusercontent.com/1211152/42754455-d0052f66-88f4-11e8-817b-788278899d4c.png">

**Comment by diasdavid** [comment]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/1211152/42754485-f03c9bac-88f4-11e8-9a26-4894eecf37fd.png">

**Comment by pgte** [comment]
No longer using the dependency that was emitting these errors.
