### ISSUE TITLE
t.content is undefined

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/peer-pad#199]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/1211152/42754507-0613a786-88f5-11e8-9e29-d37fb9310007.png">

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/1211152/42754537-26cbf35c-88f5-11e8-9381-5a16a125d3cd.png">

**Comment by pgte** [comment]
No longer using the dependency that was emitting these errors.
