### ISSUE TITLE
Seeing already piped

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/peer-pad#200]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/1211152/42754711-cfd14844-88f5-11e8-9b74-9dee543d1a99.png">

This was fixed in latest js-ipfs.

**Comment by pgte** [comment]
I haven't seen these in a while. Now using latest js-ipfs. Please reopen if you find one, and I'll keep an eye out for these. Thank you for the report! :)
