### ISSUE TITLE
Errors can cause peer-pad to silently stop working

### ISSUE THREAD

**Issue by jacobheun** [ipfs-shipyard/peer-pad#206]
When using peer-pad I received an error in the console about a y.js action not being permitted. This caused peer-pad to stop updating, but I was able to continue making edits. 

I refreshed my browser to see if I had lost data after the error and I did. We should do a better job of either recovering from the errors (the ideal) or letting the user know there was an issue and they should refresh (preferably not this).

**Comment by pgte** [comment]
We're now using peer-star-app for this, so this may have changed considerably (hopefully for the better). Please reopen this if you run into this again. Thanks!
