### ISSUE TITLE
pasting a hunk of text takes forever

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs-shipyard/peer-pad#212]
steps to reproduce:

copy the go-ipfs readme raw markdown.

paste into peerpad.

Its also really slow to delete a bunch of stuff too.

**Comment by jacobheun** [comment]
I believe this was introduced with the move to peer-star-app. I noticed the difference attempting to paste in template data after the update.

**Comment by pgte** [comment]
Working on this, close to deploying it.

**Comment by pgte** [comment]
Was batching up deltas, but that wasn't enough. Optimized at the CRDT level for batch insertion.
Should be all good now, tested it.
Please reopen if you find it's not working for you.
