### ISSUE TITLE
deploy pinner

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peer-pad#215]
Peer-star-app now has [a Pinner service](https://github.com/ipfs-shipyard/peer-star-app#pinner).
We need to deploy this to start testing it.

**Comment by pgte** [comment]
@VictorBjelkholm I think we need some of your devops magic :)

**Comment by victorb** [comment]
Latest status is over at: https://github.com/protocol/infra/issues/398

Current status: discussing with infra team about best way to deploy and move forward

**Comment by daviddias** [comment]
With this Pinner, it means that when PeerPad moves to IPLD, there has to be a migration strategy.

**Comment by victorb** [comment]
Update: The pinner has been deployed! 

> But Victor, how do we know?!

Glad you asked! If you visit https://dev.peerpad.net and start typing, you'll see a "Saving..." message popping up on the right. After a while (seconds), it'll change to "Saved!" and that's when you know that the pinner has pinned the latest state in your document.
