### ISSUE TITLE
Add greenkeeper?

### ISSUE THREAD

**Issue by jimpick** [ipfs-shipyard/peer-pad#242]
Should we add greenkeeper to this project?

**Comment by pgte** [comment]
I think we should, after #223 is merged.

**Comment by mikeal** [comment]
I'm a big greenkeeper fan, but I will warn that it can be quiet noisy. I'm used to dealing with a lot of email but if ya'll are used to a fairly clean inbox you might be in for a surprise :)

**Comment by daviddias** [comment]
Good reads on how the IPFS Community thinks about Greenkeeper:

- https://github.com/ipfs/community/issues/197
- https://github.com/ipfs/community/issues/205

(Not blocking, just for context, also today we have a different CI)

**Comment by jimpick** [comment]
It looks like it might be useful if the project has a simple set of dependencies, but is a hindrance if a project is quite complicated...

Right now, I think peer-pad has a complicated dependency set (create-react-app was ejected?) ... it would be nice to move it to something simpler over time.

Looking at the number of dependencies, it's probably best if we don't use greenkeeper for the time being and just upgrade manually on a regular basis.

**Comment by parkan** [comment]
the eject happened here: https://github.com/ipfs-shipyard/peer-pad/commit/829aa7163bab5a286fe05e44db796ae26888ba66#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

agreed on keeping greenkeeper quiet for now, especially with github's new vulnerability warnings
