### ISSUE TITLE
add me as maintainer

### ISSUE THREAD

**Issue by parkan** [ipfs-shipyard/peer-pad#244]
@jimpick I don't need to be _lead_ but I should probably have write access (and possibly admin) 😜

**Comment by jimpick** [comment]
Sure thing! I'll see if I can add you.

**Comment by jimpick** [comment]
I don't seem to have admin rights myself. /ping @pgte

**Comment by pgte** [comment]
@jimpick done

**Comment by jimpick** [comment]
Thanks @pgte! I sent an invite to @parkan as a collaborator on peer-pad with admin rights. (re-open if it should be more restrictive)
