### ISSUE TITLE
Problems syncing document title

### ISSUE THREAD

**Issue by jimpick** [ipfs-shipyard/peer-pad#252]
Sometimes, the full state of the document title sub-collaboration doesn't seem to get synced to new browsers.

Here's a video showing the issue:

https://gateway.ipfs.io/ipfs/QmbP8PtXAstgXoyHwfdoBM4umYARdycyM8HdVCNZ2EodZk/document-title-sync.mp4

This is with master at commit 0e71b5b747358890a1c50719d0f20e90536b06a2

**Comment by pgte** [comment]
Weird, will reopen this one again: https://github.com/ipfs-shipyard/peer-star-app/issues/166

**Comment by pgte** [comment]
Should be fixed now.
