### ISSUE TITLE
Hiding and showing editor breaks ability to edit

### ISSUE THREAD

**Issue by victorb** [ipfs-shipyard/peer-pad#254]
If you use the switches next to the peerpad editor to turn off the editor then turn it on again, it doesn't allow any more edits, seems the editor is disabled.

My hunch is that it's related to https://github.com/ipfs-shipyard/peer-pad/commit/805c30e22d8408b47dd8e8d9dd85dbfde148ba78

**Comment by parkan** [comment]
yep, confirm that hiding the editor view (`</>` button) and showing it again disables editing

**Comment by jimpick** [comment]
Oops. I'll fix that.

**Comment by parkan** [comment]
closed in https://github.com/ipfs-shipyard/peer-pad/pull/259#event-2009076740
