### ISSUE TITLE
Change delimiter in links so Zoom displays clickable URLs correctly

### ISSUE THREAD

**Issue by jimpick** [ipfs-shipyard/peer-pad#260]
Zoom chat really doesn't like the '-' character in PeerPad URLs... when they are posted to Zoom chat, it doesn't highlight the last part of the URL, which has the write key, which results in a read-only link, which is super confusing.

It's really a bug in Zoom, but I think maybe if we switch the delimiter to an underscore or similar, we can avoid that bug.

**Comment by jimpick** [comment]
It should be easy to do with a regex... I'll try to do it now.

**Comment by jimpick** [comment]
I coded up a complete fix... but then I discovered Zoom doesn't like the underscore either.

I experimented with the URLs a bit in a Zoom chat session, and it's actually breaking because the URLs are too long. Any portion of a URL past a certain length limit ... Zoom will chop the clickable part of the URL. :-(

I can't think of a good simple fix that doesn't involve using a URL shortener.

For now, we can just educate testers on our team to select the entire URL with their mouse and copy-and-paste it. For wider testing with Zoom users, we'll need a different solution.

**Comment by jimpick** [comment]
With '_' delimiter:

<img width="296" alt="screenshot 2018-12-07 22 54 53" src="https://user-images.githubusercontent.com/20886/49651662-2b556580-fa73-11e8-956b-e2b1b67e02a9.png">

No delimiters at all, remove slash:

<img width="296" alt="screenshot 2018-12-07 22 54 27" src="https://user-images.githubusercontent.com/20886/49651660-2b556580-fa73-11e8-868a-6a08dab95072.png">

**Comment by victorb** [comment]
@jimpick are you using the macOS client of Zoom? Seems to be a platform dependent bug in Zooms client, as the links work properly for me on Ubuntu 18.04.

![image](https://user-images.githubusercontent.com/459764/49658526-4ba00880-fa10-11e8-87ac-27f4621c234b.png)

Have we reported this to Zoom? It's clearly not a good behaviour in the client, maybe they'll be able to solve it quickly.

**Comment by jimpick** [comment]
I couldn't find a good bug reporting form, so I sent an email to info@zoom.us.

**Comment by jimpick** [comment]
I received a response from Zoom: "Our engineers have told me that this is a known issue and that it will be fixed in an update before too long."

**Comment by jimpick** [comment]
I tested with the current version of Zoom, and it's fixed, so I'm closing this.
