### ISSUE TITLE
Move ipfs-shipyard/peer-pad -> peer-base/peer-pad ?

### ISSUE THREAD

**Issue by jimpick** [ipfs-shipyard/peer-pad#270]
Should we relocate to the peer-base org?

**Comment by pgte** [comment]
I'm not sure, but I tend to think not. Eventually we'll start out extracting pieces from peer-base, not sure if apps should live alongside libraries.. Not 100% sure of this..

**Comment by jimpick** [comment]
Closing this. I'm fine with leaving it on ipfs-shipyard for now.
