### ISSUE TITLE
Paste is broken ... only last character gets committed to document

### ISSUE THREAD

**Issue by jimpick** [ipfs-shipyard/peer-pad#276]
If I paste in some text on master, only the last character shows up in the document.

I suspect it's related to my CRDT "fix" https://github.com/ipfs-shipyard/js-delta-crdts/pull/34

**Comment by jimpick** [comment]
Fixed with this PR: https://github.com/ipfs-shipyard/js-delta-crdts/pull/35

**Comment by pgte** [comment]
@jimpick I don't think it's required, but please tell me if you need a new patch release of peer-base.

**Comment by jimpick** [comment]
I think if I just update package-lock.json, that should do a deploy...

**Comment by jimpick** [comment]
This is fixed.
