### ISSUE TITLE
Unexpected local state causes editor rendering error

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/peer-pad#28]
Works in Chrome

<img width="1120" alt="screen shot 2017-10-16 at 10 50 06" src="https://user-images.githubusercontent.com/152863/31606037-de02480e-b25f-11e7-8fc1-429ae169f0a6.png">

**Comment by pgte** [comment]
@alanshaw cannot reproduce locally with latest Firefox.
I'm not sure what caused this, but just so we eliminate all other causes, did you try wiping all storage?

**Comment by alanshaw** [comment]
Yep, it started working when I wiped Indexed DB storage

**Comment by olizilla** [comment]
I had the same issue with chrome, and again, wiping indexed DB fixed it. I'm updating then title of this issue, as I don't think it's firefox specific.

**Comment by olizilla** [comment]
More specifically this happened when we started working on the project and hasn't happened since, and may have been cause by having data from older / unstable versions of ipfs-js in our browsers.
