### ISSUE TITLE
Use our own CI/CD pipeline

### ISSUE THREAD

**Issue by parkan** [ipfs-shipyard/peer-pad#287]
The main Jenkins cluster has been intermittently (but often) failing the pin/publish stage, blocking us from deploying an up-to-date dev.peerpad.net and pinner. This is unlikely to be fixed soon.

We could set up our own CI/CD pipeline to handle these deployments. The current flow is described in [DEPLOY.md](https://github.com/ipfs-shipyard/peer-pad/blob/e65fa08e6bce4627b58e6e82e0fdc0382a3b828f/docs/DEPLOY.md) (this seems to be mostly up to date, except that master updates dev.peerpad.net and production is the one that drives the main site).

We can either:
- replicate the publish-to-IPFS [flow from Jenkins](https://github.com/ipfs/jenkins-libs/blob/796cab23030077109f98bbb092d57ed9f4964772/vars/website.groovy#L80) on circle/travis (I think this is possible? I remember doing this for mediachain) << this is the "right" way
- just deploy the whole thing to heroku for now to get it working (the pinner and web app can be co-located this way)

NOTE: I currently don't know how the pinner is deployed (@victorb ?). I'm also not sure if we need to run any other supporting infra (signaling/relay servers), they seem reasonably well-covered by infra

this would fix #240

**Comment by jimpick** [comment]
I believe the pinner is deployed via Travis:

https://github.com/peer-base/peer-base/blob/master/.travis.yml

**Comment by parkan** [comment]
ahh I literally looked at that file but didn't think the pinner was in there because... it's not a pinner-specific repo?

**Comment by jimpick** [comment]
It would be a good time to think about splitting it out into a separate repo, especially if we want to add non-generic features to it for our specific deployment.

**Comment by parkan** [comment]
given our inclination towards small repos I'd agree with splitting it out, regardless of whether it's generic or not

**Comment by pgte** [comment]
@jimpick we could create peer-pad-pinner, which is just a including the peer-base pinner. This would be good to just decouple the releases of the pinner and the app itself.

**Comment by jimpick** [comment]
PR #294 moved the deploy to CircleCI.
