### ISSUE TITLE
CircleCI deploy to dev.peerpad.net failing ... 

### ISSUE THREAD

**Issue by jimpick** [ipfs-shipyard/peer-pad#295]
@olizilla: I merged #294 to master to see if it would deploy to dev.peerpad.net.

https://circleci.com/gh/ipfs-shipyard/peer-pad/310

It appears to have failed when it tried to configure the DNS:

```
error: did not find account for: dev.peerpad.net
```

**Comment by parkan** [comment]
needs to update the `dev` record in the `peerpad.net` zone

**Comment by jimpick** [comment]
I modified the deploy script here:

https://github.com/ipfs-shipyard/peer-pad/commit/47d29e451ded0be30b59e69bfd326a2ed933ed7b

It appears to have been successful:

https://circleci.com/gh/ipfs-shipyard/peer-pad/312

```
$ dig +short _dnslink.dev.peerpad.nettxt
"dnslink=/ipfs/QmeWR3gKDGoSn2QyCWiT4d2N8UHzAEECqzViq1jZ6P8a6U"
```

However, the page isn't loading for me.

https://dev.peerpad.net/

I wonder if the 'A' record for dev.peerpad.net is pointing to the correct place?

```
$ dig +short dev.peerpad.net
209.94.90.1
```

**Comment by jimpick** [comment]
I think everything is correct ... I think the gateway is just loading terribly slowly:

https://dev.peerpad.net/

**Comment by olizilla** [comment]
thats somewhat good. At least peerpad can auto deploy once more.

**Comment by parkan** [comment]
everything is looking good to me right now, closing this
