### ISSUE TITLE
Improve 3rd bullet color to be accessible/readable

### ISSUE THREAD

**Issue by momack2** [ipfs-shipyard/peer-pad#299]
![Screen Shot 2019-03-13 at 2 51 13 PM](https://user-images.githubusercontent.com/618519/54306321-79f92b00-459f-11e9-9cc1-d3ac28378de5.png)
Please change purple color to something readable against the navy background (maybe lilac or pink?). You can use online accessibility tools ([example](https://webaim.org/resources/contrastchecker/)) to ensure the the color contrast between the background and the font is readable.

**Comment by jbenet** [comment]
yeah this is really hard to see

**Comment by parkan** [comment]
https://github.com/ipfs-shipyard/peer-pad/issues/271
