### ISSUE TITLE
Links from actively edited peerpads should have different landing place than blank entry

### ISSUE THREAD

**Issue by momack2** [ipfs-shipyard/peer-pad#305]
When you are sent and click on a peer-pad link that points to an active doc that is being shared with you - the redirect/loading page should look **different** than a blank peer pad. The UX problem is that you are following a link that someone sent you to notes and on first load it looks like a blank/empty peer-pad - which gives the impression that all the previously added data has been lost, or you were sent a wrong link (without a reference to the specific doc).

Instead, when editing a peerpad, the link in the URL bar / in the "share" button should have some sort of special marker that differentiates it from a brand fresh peerpad doc. On click of that link, there should be a "loading" screen while IPFS tries to find the document content in the DHT - only after timeout should the user be prompted to create a blank peer pad (and I assume it will have a different weblink, no?)

**Comment by parkan** [comment]
https://github.com/ipfs-shipyard/peer-pad/issues/266
