### ISSUE TITLE
deploying peerpad

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/peer-pad#46]
Deploying Peerpad should be done through our standard way of publish to IPFS and dnslink, the same way our websites get deployed (e.g https://github.com/ipfs/website#usage)

For that we need:

- [x] Add peerpad.net to DNSSimple (@lgierth ?)
- [x] @pgte to create a DNSSimple account so that we can share ownership with him
- [ ] Makefile with make build, make deploy and make publish-to-domain script

**Comment by pgte** [comment]
We need a certificate also, right?
How is that usually processed?

**Comment by lgierth** [comment]
> We need a certificate also, right?

It's not automated yet, I'll take care of it for the time being

**Comment by lgierth** [comment]
Cert is in place: https://peerpad.net and you have access to DNSimple to update the dnslink record - only thing missing is the makefile and dnslink script.

My job here is done :):)
