### ISSUE TITLE
Snapshot loads blank page

### ISSUE THREAD

**Issue by lgierth** [ipfs-shipyard/peer-pad#85]
This snapshot https://gateway.ipfs.io/ipfs/QmcUFDWoXUKZuqXV16FzsyLuV8SHVPqywf5UVDoV6Wqsid/#88zG4sQJ3AkY48mzEoL3CLSrus5cHHYTS24TXxfVhg6mjszxGLT3P4gS1uwzXj9u2i loads an empty page in Firefox Quantum 57.0b12 (64-bit).

It successfully requests:
- the snapshot itself: https://gateway.ipfs.io/ipfs/QmcUFDWoXUKZuqXV16FzsyLuV8SHVPqywf5UVDoV6Wqsid/#88zG4sQJ3AkY48mzEoL3CLSrus5cHHYTS24TXxfVhg6mjszxGLT3P4gS1uwzXj9u2i
- normalize.css: https://ipfs.io/ipfs/QmZuSAW5kpxzaidmrpqoWmk8q5Yk7qqpGyxX3zRnRjnRVE

No output in the console.

---

(On a sidenote it would be great to include any dependency in the snapshot DAG itself, so that they get included when pinning the snapsht.)

**Comment by pgte** [comment]
Should be working now
