### ISSUE TITLE
File encryption.

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/peer-pad#9]
The file upload feature should also encrypt the files, otherwise a file that is uploaded is stored on the network in plaintext. This creates the UX challenge that if a user grabs the hash of the file uploaded to the UI, it won't be able to be resolved. I think we can do something better.

What if when the user uploads a file, we upload a self decrypting image loader (that picks the key from the url, same as the pads), but if the image is being loaded from the pad itself, it knows how to pick the imagine from the graph and renders that accordingly? This way, when a user uploads a file, the graph would have a structure similar to:

```
Qmhashasdas
├── index.html  # page that knows how to decrypt the image with the key on the hash
├── file-uploaded
...
```

@pgte thoughts?

**Comment by pgte** [comment]
Good point!
Being encrypted, the pad should be able to load all the images itself, without having to load a loader, and the image should be in the graph of the document.

I think this is enough. An image is stored under the doc graph, encrypted using the same key as the document itself.

I'm failing to see the need of generating a separate self-contained image loader, do you?

**Comment by diasdavid** [comment]
> I'm failing to see the need of generating a separate self-contained image loader, do you?

I believe that users will want to share direct links to the documents once they upload them, as they are used to do through IPFS. It will be a surprise for the user when the CID of a document doesn't return a doc but rather a blob of encrypted text.

**Comment by pgte** [comment]
@diasdavid Good point.

**Comment by pgte** [comment]
Done
